collection = [
    "sessions/*guthrie",
    "sessions/*hunger",
    "sessions/*arvo-part",
    # "sessions/*goblet-ch11",
    # "sessions/*goblet-ch3",
    # "sessions/*linguaphone-german",
    # "sessions/*quran",
    # "sessions/*harry-potter",
    # "sessions/*sherlock",
    # "sessions/*brave-ch1-4",
    # "sessions/*neuromancer-ch1-3",
    # "sessions/*lindgrens-favoriter-hela",
    # "sessions/*utvandrarna-02",
    # "sessions/*roda_rummet2",
    # "sessions/*NIN",
    # "sessions/*gulliver",
]
