playlist = [
    {"session": "sessions/*neuromancer-ch1-3",
     "args": "-z 3"},
    {"session": "sessions/*brave-ch1-4",
     "args": "-z 0.5"},
    {"session": "sessions/*brave-ch5-8",
     "args": "-z 1"},
    {"session": "sessions/*1984-ch1-3",
     "args": "-z 0.3"},
    {"session": "sessions/*gatsby-ch1-5",
     "args": "-z 0.5"},
    {"session": "sessions/*gatsby-ch6-10",
     "args": "-z 0.5"},
    {"session": "sessions/*gatsby-ch11-15",
     "args": "-z 0.5"},
    {"session": "sessions/*art-of-war",
     "args": "-z 1"},
    {"session": "sessions/*rings",
     "args": "-z 0.5"},
    {"session": "sessions/*sherlock",
     "args": "-z 0.5"},
    {"session": "sessions/*frankenstein",
     "args": "-z 0.25"},
    {"session": "sessions/*quran",
     "args": "-z 0.25"},
    {"session": "sessions/*learn-in-car*",
     "args": "-z 0.2"},
    {"session": "sessions/*hobbit*",
     "args": "-z 0.25"},
    {"session": "sessions/*hunger",
     "args": "-z 8"},
    {"session": "sessions/*miracle",
     "args": "-z 5"},
]
