playlist = [
    {"session": "sessions/*sherlock",
     "args": "-z 0.5"},
    {"session": "sessions/*frankenstein",
     "args": "-z 0.25"},
    {"session": "sessions/*quran",
     "args": "-z 0.25"},
    {"session": "sessions/*learn-in-car*",
     "args": "-z 0.2"},
    {"session": "sessions/*hobbit*",
     "args": "-z 0.25"},
    {"session": "sessions/*hunger",
     "args": "-z 8"},
    {"session": "sessions/*miracle",
     "args": "-z 5"},
]
