env = Environment()
env.Append(LIBS = ['glut', 'liblo'])
env.Program(target = 'visualizer',
            source = ['Visualizer.cpp',
                      'GlWindow.cpp',
                      'Stopwatch.cpp'])
